### PR TITLE
Add id / name based auto filling.

### LINKED ISSUE #138: Feature: Extend custom fields usage to form autofill
### Steps to reproduce
1. Open up a multi input field form

### Expected behaviour
Custom field with matching label should be inserted

### Actual behaviour
Custom fields won't get matched to actual form

### Configuration
**Operating system**:  Ubuntu

**Browser**: Chrome

**Extensions that might cause interference**: 

**Passman version**: 2.1.2

**Extension version**:  2.0.1

**Nextcloud version**: 12.0.0
   

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/47546152-feature-extend-custom-fields-usage-to-form-autofill?utm_campaign=plugin&utm_content=tracker%2F52236699&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52236699&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anonymous-one**
Adds id / name based element auto filling. Custom fields that have a label that starts with a hash (#) are automatically searched for in the page and if found, are auto filled.

Fixes #138

### CODE REVIEW

**Comment by brantje** [comment]
Thanks! I'll will sign the commits for you.

**Comment by anonymous-one** [comment]
Thanks I appreciate it.

I'll make a few improvements next week once I free up some more time.

**Comment by anonymous-one** [comment]
How do I get past continuous-integration/drone/pr — the build failed.

When I try to click the login under details it says failed to login.

**Comment by brantje** [comment]
That drone checks if the commits are signed. 
Unfortunately you can't sign your commits via web. 
If you would more information about signing your work you can look here:
https://help.github.com/articles/signing-commits-with-gpg/

**Comment by brantje** [comment]
I merged, and squashed the merge request, however, github didn't auto close this PR.
Commit is here: https://github.com/nextcloud/passman-webextension/commit/5cd6e6a2a28d5a63c25a8611583450c1e351f81c

**Pull request closed without merging**
