### PR TITLE
Don't send cookies to HTTP API

### LINKED ISSUE #258: TypeErorr: Failed to fetch
### Steps to reproduce
1. Sync passwords
2. ??
3. Profit

### Expected behaviour
Passwords should sync

### Actual behaviour
An error message with "TypeError: failed to fetch" in it appears and the sync doesn't succeed.

### Configuration
**Operating system**: Debian Linux

**Browser**: Chrome 68.0.3432.3

**Extensions that might cause interference**: None?

**Passman version**: 2.1.4

**Extension version**: 2.1.1

**Nextcloud version**: 13.0.2
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

Not sure how to get the chrome network log, but the apache access log shows a bunch of 302 responses on hitting the passman refresh button.

eg:

[24/May/2018:10:32:40 -0600] "GET /index.php/apps/passman/api/v2/vaults/[snip] HTTP/1.1" 302 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3432.3 Safari/537.36"

```
</details>   

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58788386-typeerorr-failed-to-fetch?utm_campaign=plugin&utm_content=tracker%2F52236699&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52236699&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #269: [0] TypeError: Failed to fetch
### Steps to reproduce
1. Update to Chrome 68
2. Restart the browser
3. Issue appears

### Expected behaviour
As soon as the update is completed and the browser is restarted, I should be able to get the logins from passman.

### Actual behaviour
As soon as the update is completed and the browser is restarted, I get the message: Ungültige Antwort des Servers: [0] TypeError: Failed to fetch or connection timeout.

### Configuration
**Operating system**: Windows 10 Pro 64 Bit

**Browser**: Google Chrome 68.

**Extensions that might cause interference**: None.

**Passman version**: 1.2.4

**Extension version**: 2.1.1

**Nextcloud version**: 13.0.5
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/61330301-0-typeerror-failed-to-fetch?utm_campaign=plugin&utm_content=tracker%2F52236699&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52236699&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by marcelklehr**
Fixes #269
fixes #258

Happy keepyourpasswordssafe-ing again :)

### CODE REVIEW

**Comment by wjwieland** [comment]
So this is confirmed fixed on all platforms?  

Version 68.0.3440.75 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Passman still coming back with:
Invalid response from server: [0] TypeError: Failed to fetch when re-installing the extension and trying to set up.

**Comment by marcelklehr** [comment]
@wjwieland Did you build and install the latest version or the patch I'm proposing here? The patch hasn't been reviewed, applied nor released, yet.

**Comment by nhasbun** [comment]
I applied this manually and it's working without problems on a Windows 10 machine.

**Comment by wjwieland** [comment]
@marcelklehr 
No, I did not.  I am simply a user for which the current version (production) works on Google browser on Windose 10, but not in any version of Chromium nor Google Chrome on any version of Linux which is my main working platform.  None of the Linux/Google combo's allow me to even set up (after uninstall) passman.  They return the error mentioned in my previous post.  I run the stable versions of all browsers on all platforms.

Essentially, my question is: Is this patch being tested on Linux/(browser-whatever)?

Thanks for your work on this.  I count on passman and it is a real downer not having had it work for some time now.

**Comment by marcelklehr** [comment]
> Essentially, my question is: Is this patch being tested on Linux/(browser-whatever)?

Yes. :)

**Comment by wjwieland** [comment]
@marcelklehr 
Thank you! :-)

**Comment by jzielke-nli** [comment]
@marcelklehr When will the fix be included in the chrome web store?

**Comment by marcelklehr** [comment]
@jzielke-nli Ah, the github UI is a bit misleading here. I'm a nextcloud org member, but I'm not a passman maintainer. @brantje should be able to answer this one.

**Comment by jamaale** [comment]
Add me to the group of when will the patch finally be available. :/

**Comment by jzielke-nli** [comment]
@brantje Please be so kind and publish the extension with that fix. All passman users have been sitting around with Chrome 67 for almost a month since version 68 came out. Thanks!

**Comment by Freeben666** [comment]
How can I rebuild the extension myself ? 

I tried swapping the api.js file in the extension folder in AppData, but Chrome noticed and declared the extension as corrupted...

When I try packaging the extension within Chrome, from the files cloned from Github, I get an error : "Variable $USERNAME$ used but not defined."

**Comment by marcelklehr** [comment]
You'll need to install node.js and npm, clone the repo, run `npm install`, `npm install -g grunt`, then run `grunt build`, judging from the files in the repo. I'm not sure if you already have the extension files ready at that point or if you still need to package the result.

**Comment by Freeben666** [comment]
Thank you jzielke, but being quite paranoid, I doubt I'll be using a pre-built unofficial version. I have a hard enough time trusting the official one with all of my passwords.

**Comment by jzielke-nli** [comment]
@Freeben666 I'm aware of that. Just trying to help out a bit. Had the chance to meet @animalillo once personally and he asked me for contribution. I'd offer admin privileges for this Jenkins project to the devs so they can do code-proofing and integrate this project officially using sha256 checksums.

**Comment by nhasbun** [comment]
Stuck with Chromium here.

I know developers have a lot of work but this is a direct functionality issue. Can't use passman on Chrome at all since v68. You can still manually download the extension but you have a constant notification message on Chrome at start.

**Pull request merged**
