### PR TITLE
l10n: Correct spelling

### PR DESCRIPTION
**Pull request by Valdnet**
Reported by a Transifex translator.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]

**Comment by rakekniven** [comment]
Looks like this app is not maintained actually.

**Comment by Valdnet** [comment]
So I close.

**Comment by blizzz** [comment]
> @blizzz Who can give write access to this repo to add a note about being unmaintained?

ideally if @brantje could set this in stone?

**Comment by rakekniven** [comment]
Ok. @brantje Hopefully you are still reading this comments here. Please give us a sign :thanks:

**Pull request closed without merging**
